### ISSUE TITLE
Rendering widgets without generated container

### ISSUE THREAD

**Issue by Rolice** [Arrilot/laravel-widgets#13]
Hello, I have a problem with the widgets while rendering.  On this stage a container is placed, inside of which the view output is rendered. This container, however, sometimes breaks the layout, for example in lists used with dropdown menus.

Is it possible to control this behavior of the widget?

PS: I assume this is used with reload feature and async widgets, but could it be ignored for static widgets?

**Comment by arrilot** [comment]
> PS: I assume this is used with reload feature and async widgets

Right. Unfortunatelly there is no real way to get rid of the container at the moment.
I'll try to make some improvements as soon as I get enough time.

At the moment you can try to solve your issue with CSS. The container has `arrilot-widget-container` class.

Another alternative is to downgrade to `~2.4` since there is no containers for simple widgets in those versions.

**Comment by Rolice** [comment]
Thank you for your response!
I will try forking the project and applying a solution, if I get spare time.

**Comment by arrilot** [comment]
I've just tagged a 2.8.0 release https://github.com/Arrilot/laravel-widgets/releases/tag/2.8.0
Feel free to update!

Btw, I'm gonna release 3.0 really soon too with several noticable changes.

**Comment by Rolice** [comment]
Thank you! I am pulling the package right now. :)

**Comment by arrilot** [comment]
3.0.0 is here https://github.com/Arrilot/laravel-widgets/releases/tag/3.0.0
Gonna hold off on this for now,
