### ISSUE TITLE
Question - Push new data to widget

### ISSUE THREAD

**Issue by danielroymoore** [Arrilot/laravel-widgets#36]
This is a brilliant library, I was wondering if there is anyway to make the Re-loadable widget query a data set for changes before reloading?

**Comment by arrilot** [comment]
Hi, what do you mean when you say "to query a data set for changes before reloading"?

**Comment by danielroymoore** [comment]
Cheers for getting back to me, I've amended the question a little bit as I wrote it in a rush. I thought of two use cases that I'm trying to achieve that aren't immediately obvious ( or they are, but it seem I'm going about it wrong).

For example: I have a reloading widget that is reading values from a data set. At present, after the timeout the widget will refresh. However what I'd like is to query the table for changes and only call the run function if there has been a change since the last reload. My work around off the top of my head is:

```
protected $timeLastModified;

public function pollData()
{
    // Check last modified of some data source, update $timeLastModified if applicable and return a bool
}
public function run()
{
    if (pollData()) {
        return view("widgets.recent_news", [
            'config' => $this->config,
        ]);
    }
}
```

Is there are way of hooking up run function of a widget to Events in Laravel, so that the need for the above is not needed. This may remove the need to put this type of functionality within a reloading widget.

**Comment by arrilot** [comment]
``` php
public function run()
{
    if ($this->pollData()) {
        return view("widgets.recent_news", [
            'config' => $this->config,
        ]);
    }
}
```

The problem is that it doesn't stop the widget from being reloaded. It's gonna be replaced with the blank content in this case. The widget MUST be reloaded each time to attach another `setTimeout()` handler for the next iteration.

So, there is nothing I can do for you here I'm afraid.

If you really need to do an extra check before reload just do it manually.
1) Make widgget not reloadable
2) Write your own javascript reloader using `setInterval()`. Make an ajax call to check state and reload widget manually by another ajax if it's needed.
Not a big deal.
