### ISSUE TITLE
Pass params to async widgets properly

### ISSUE THREAD

**Issue by Clarence-pan** [Arrilot/laravel-widgets#52]
_DELETED_

**Comment by arrilot** [comment]
Thanks for bringing this up.

I'll see what can be done here.

**Comment by Clarence-pan** [comment]
@arrilot It's OK. I've made a temporary solution using JSON: https://github.com/Clarence-pan/laravel-widgets/commit/b9cd6d89df514f180fb755dcd31aac5696810676.

**Comment by arrilot** [comment]
I've fixed it a little bit differentl
https://github.com/arrilot/laravel-widgets/commit/5cddda5bf1c89ea0488d7c3ce3009567075f5c00
but it's not tagged yet.

1) I don't see any need in str_replace'ing anything because
http_build_query is used.
2) Encrypt is better than base64_encode because it effiectively prevents
malicious user from stealing  widget params on the client if they are
sensitive.

Any feedback?

2016-07-31 10:20 GMT+03:00 Clarence Pan notifications@github.com:

**Comment by Clarence-pan** [comment]
1) If there is no `str_replace`, it will also be OK. But I don't like it because it is a little longer as `'+/='` will be encoded to '%2B%2F%3D'. I don't like %%%%..

2) Any other encrypt methods should also work. I just choose a fast and good-like one -- Base64. But I don't think the widget params need to be protected.

**Comment by arrilot** [comment]
Thanks
