### ISSUE TITLE
default_namespace not working correctly

### ISSUE THREAD

**Issue by DigicreateJens** [Arrilot/laravel-widgets#83]
Hey!

I'm trying to use your package in combination with the [nwidart/laravel-modules package](https://github.com/nWidart/laravel-modules), but I'm getting an error when trying to set the `default_namespace` to `Modules\Foo\Widgets` and using the `make:widget BarWidget` command.

This is pretty unfortunate, because the combination of Modules and Widgets seems like a strong one if this could be fixed.

If you need any more info, let me know!

**Comment by arrilot** [comment]
Unfortunately there is no easy way to generate a widget using generator if the default namespace is outside of application namespace (typically it's `App` if you haven't changed it).
Laravel's generator simply does not support it.

The good part is that the rest of the package works fine with Widgets placed in `Modules` folder, just generator is lacking.

So you can set the default namespace to `Modules`, create widgets via copy-paste and call them like that `@widget('blog.widgets.list')`

Hope that helps.

I've also added a quick check to the generator. 
It throws a descriptive exception now instead of falling into infinite loop

**Comment by longlp-sosene** [comment]
Hi, I have the same problem with nwidart/laravel-modules when trying to move Widgets folder to inside the Modules.
The namespace of widget is 

```
<?php

namespace Modules\Contract\Widgets;

use Arrilot\Widgets\AbstractWidget;

class BadgeContractNumber extends AbstractWidget
{
    /**
     * The configuration array.
     *
     * @var array
     */
    protected $config = [];

    /**
     * Treat this method as a controller action.
     * Return view() or other content to display.
     */
    public function run()
    {
        //

        return view('widgets.badge_contract_number', [
            'config' => $this->config,
        ]);
    }
}
```

I have tried to register via service provider but it's not work

```
foreach (Module::allEnabled() as $module) {
      app('arrilot.widget-namespaces')->registerNamespace($module->getName(), '\App\Modules\\'. $module->getName() .'\Widgets');
}
```

And this is how i try to call widget
```
@widget('Contract.Widgets.badgeContractNumber')
@widget(Contract::badgeContractNumber')
```
The only one I can call to the Module Widget is
`@widget('Modules\Contract\Widgets\badgeContractNumber');`
But it cant render the view inside resouces (Modules/Contract/Resouces/views/widgets)
